import Header from '@/src/Header'
import Head from 'next/head'
import styled from 'styled-components'



export default function Home() {
  return (
    <>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com"/>
      <link href="https://fonts.googleapis.com/css2?family=Mukta:wght@300;400;600&display=swap" rel="stylesheet"/>        
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/Home/vscode-svg-icon.svg" />
      </Head>
      <Header/>
      <div>
        Hello World.
        <a href="https://google.com">Teste</a>
      </div>
    </>
  )
}
