import Banner from '@/src/Banner'
import CarouselHome from '@/src/CarouselHome'
import DownloadSection from '@/src/DownloadSection'
import Footer from '@/src/Footer'
import Header from '@/src/Header'
import MainReasons from '@/src/MainReasons'
import Head from 'next/head'
import styled from 'styled-components'



export default function Home() {
  return (
    <>              
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/Home/vscode-svg-icon.svg" />
      </Head>

      <Header isHomePage={true}/>
      <Banner/>
      <CarouselHome />
      <MainReasons />
      <DownloadSection />
      <Footer />
    </>
  )
}
